### ISSUE TITLE
Where should this line go?

### ISSUE THREAD

**Issue by storrence88** [DmitryTsepelev/ar_lazy_preload#26]
```
ArLazyPreload.config.auto_preload = true
```

Should this line go in the config block in `application.rb`?

**Comment by DmitryTsepelev** [comment]
Hi Steven! Sorry, there was a long weekend here in Russia 😅Just for the future references—this like could either go to the `application.rb` or to one of initializers

**Comment by storrence88** [comment]
Thank you @DmitryTsepelev! 🙏I ended up putting in an initializer.
