### ISSUE TITLE
Migrate Travis to GitHub Action

### ISSUE THREAD

**Issue by PikachuEXE** [DmitryTsepelev/ar_lazy_preload#44]
https://www.reddit.com/r/ruby/comments/jt2uub/deep_dive_moving_ruby_projects_from_travis_to/

Travis will no longer be free for Open Source projects (And it's already slow for OS projects now)
This is to move to GitHub Action for CI

Example: https://github.com/PikachuEXE/where_lower/blob/master/.github/workflows/tests.yaml
This example contains multiple ruby versions & gemfiles
But since this project's Travis config matrix is quite complex
I am too lazy to convert it :P

**Comment by DmitryTsepelev** [comment]
I'll do my best to change the CI this week, thanks you for pointing it out 🙂

**Comment by DmitryTsepelev** [comment]
@PikachuEXE Here is an attempt #45. I've also deprecated Rails 4.2 support (because it want an old bundler), could you please take a look when you have a moment?
