### ISSUE TITLE
explain how this differs from goldiloader

### ISSUE THREAD

**Issue by grosser** [DmitryTsepelev/ar_lazy_preload#5]
I've been using https://github.com/salsify/goldiloader for a while so I was curious how this project is different or if it offers any advantages ?

**Comment by DmitryTsepelev** [comment]
Hi! Thanks for your interest 🙂 to be honest, I haven’t heard about goldiloader when started working on this, and the idea was different - to allow perform lazy preloading by defining associations explicitly. Some time later I’ve bumped into goldiloader and decided to add that similar magic option (it was literally one-line change based on the existing functionality)

**Comment by grosser** [comment]
thx, maybe the projects can merge somehow, it's a complex problem that needs lots of eyes to get right :)

**Comment by bf4** [comment]
curious what's changed here in the last year plus.  Maybe we just add to the readme: "What about goldiloader? Answer: I don't know. They're both probably fine"
