### ISSUE TITLE
Using without Rails

### ISSUE THREAD

**Issue by taylorthurlow** [DmitryTsepelev/ar_lazy_preload#51]
Is a full Rails dependency actually necessary for this gem to function? Would love to use it but I'm in the simpler Rack-app land.

**Comment by DmitryTsepelev** [comment]
Technically we need only ActiveRecord, which relies on ActiveSupport and ActiveModel. I guess it should be possible to relax dependencies, PRs are welcome 🙂

**Comment by taylorthurlow** [comment]
Opened #52.
