### ISSUE TITLE
Global auto preload behavior

### ISSUE THREAD

**Issue by vala** [DmitryTsepelev/ar_lazy_preload#57]
Hi @DmitryTsepelev,

I'm using the global auto preload feature (`ArLazyPreload.config.auto_preload = true`) in a large project, and am very happy with the performance gain that it provides.

Nevertheless, since I enabled this feature, I'm fixing bugs related to auto preloading quite often, most of which are because of  some interactions with other gems. I think that I can count the time spent in fixing those bugs in days.

For now I think that the balance between the performance / maintenance gain is still good to keep the feature enabled, but I'm starting to think about disabling it and going the manual way if I still find such issues.

I was thinking that it could be a good thing to add a warning in the README about this feature to inform people about the risks of using the feature, as it can create hard to trace bugs.

What do you think about it ?

**Comment by DmitryTsepelev** [comment]
Hi @vala!

Would be nice to have a list of incompatible gems included to the README, technically "THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND" is the part of the license 😉

**Comment by vala** [comment]
Hi !

Yes my idea is just to have a simple warning to avoid people losing too much time with the feature, or dropping the gem altorgether if they can't understand why some auto preload cases are generating errors.

For the gems incompatibility, I don't know how to think about it, as for the cases I encountered, there are just some edge cases that raise errors, the general and simple cases often work as expected.

**Comment by DmitryTsepelev** [comment]
Sure, do you want to add this line? 🙂

**Comment by quentindemetz** [comment]
@DmitryTsepelev would it be possible to specify that we want to use this only for `ApplicationRecord` (from which all the app's model descend), which should not interfere with other gems?
