### ISSUE TITLE
Record reload broken with 1.1.0

### ISSUE THREAD

**Issue by PikachuEXE** [DmitryTsepelev/ar_lazy_preload#62]
https://github.com/rails/rails/blob/v7.0.4/activerecord/lib/active_record/persistence.rb#L943
Rails definition has arguments

https://github.com/DmitryTsepelev/ar_lazy_preload/blob/v1.1.0/lib/ar_lazy_preload/active_record/base.rb#L16
1.1.0 of this gem doesn't

**Comment by DmitryTsepelev** [comment]
Uh, sorry for that, no more midnight released 🥱https://github.com/DmitryTsepelev/ar_lazy_preload/pull/63 should be a fix, will roll out now
